### ISSUE TITLE
«194998, a virtual product, i can now change to Processing Virtual Product, but cant complete the order»

### ISSUE THREAD

**Issue by dmitrii-fediuk** [canadasatellite-ca/site#255]
[upwork.com/messages/rooms/room_7725f00c5ed18ba32b7c46f038311707/story_37e740c576c661f9ab29cf00951c8d5d](https://www.upwork.com/messages/rooms/room_7725f00c5ed18ba32b7c46f038311707/story_37e740c576c661f9ab29cf00951c8d5d)
It could be related to https://github.com/canadasatellite-ca/bambora/issues/10

**Comment by dmitry-fedyuk** [comment]
![06](https://user-images.githubusercontent.com/83204/137626433-314cf2b4-9ab8-4e43-9c4a-4d9489150510.png)

**Comment by dmitry-fedyuk** [comment]
```sql
UPDATE sales_order
SET state = 'complete'
WHERE state = 'processing' AND status = 'complete_virtual';
```
